### ISSUE TITLE
10.24 Mac client  Unable to connect

### ISSUE THREAD

**Issue by popokicn** [0blu/WinterspringLauncher#40]
BasePath: /Users/van/WinterspringLauncher
Found client (mac) in /Users/van/WinterspringLauncher/World of Warcraft 1.14.0
Unable to patch '/Users/van/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv' (WinterspringLauncher.HermesDataPatches.Hotfix.ItemEffect1.csv)
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/van/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllLines(String path, Encoding encoding)
   at WinterspringLauncher.LauncherActions.<PrepareHermesProxyData>g__PatchCsvFiles|19_2(List`1 patchResources, String replace, String csvDirPath, <>c__DisplayClass19_0&) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 449
   at WinterspringLauncher.LauncherActions.PrepareHermesProxyData(String hermesPath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 417
   at WinterspringLauncher.Launcher.<>c__DisplayClass1_0.<Main>b__5() in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 72
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 152
>>> Failed to prepare HermesProxy Data, continuing anyways (might not work) <<<

**Comment by popokicn** [comment]
It doesn’t work even after re-downloading, and I can’t connect to Asia either.Many people have encountered this, please help me solve it

**Comment by alpergk** [comment]
Hi @popokicn i was trying to find a solution and i found a temporary one.BEFORE THESE STEPS(Copy and save your WTF Folder in WoW, Addons and AccountData in hermes-proxy folder you gonna replace them later to save your completed quests game settings addon settings etc.) Try this go into HD(Hard Drive) -> Users -> User(For my id) -> WinterspringLauncher -> hermes-proxy -> HermesProxy-MacOS-v3.10(Copy all stuffs here) then go back to hermes-proxy part again and paste them here. Also go into CSV folder and copy all stuffs here and find __MACOSX folder within the hermes-proxy. Then -> HermesProxy-MacOS-v3.10 -> CSV -> Hotfix paste all stuff here. Now recover your saved variables like i mentioned before Addons,AccountData etc. Now you can play the game use terminal thing to open the game. BUT some strange bug here. If u already click the icon on the wow login screen remember my account name, untick it. If you struggle when you first time trying to login it will say connecting but it wont connect dont wait. Just cancel it untick the remember account name part and reopen the game and write your account name manually all the time until this strange bug fix. Hope it works cuz it worked on me (M1 Pro MacBook)

**Comment by popokicn** [comment]
Thank you very much. I have logged in. I will post this method to the kook forum so that other players can log in. Thanks again.
&nbsp;


è?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alper ***@***.***&gt;; 
发送时间: 2023年10月24日(星期二) 凌晨4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [0blu/WinterspringLauncher] 10.24 Mac client  Unable to connect (Issue #40)





 
Hi @popokicn i was trying to find a solution and i found a temporary one.BEFORE THESE STEPS(Copy and save your WTF Folder in WoW, Addons and AccountData in hermes-proxy folder you gonna replace them later to save your completed quests game settings addon settings etc.) Try this go into HD(Hard Drive) -&gt; Users -&gt; User(For my id) -&gt; WinterspringLauncher -&gt; hermes-proxy -&gt; HermesProxy-MacOS-v3.10(Copy all stuffs here) then go back to hermes-proxy part again and paste them here. Also go into CSV folder and copy all stuffs here and find __MACOSX folder within the hermes-proxy. Then -&gt; HermesProxy-MacOS-v3.10 -&gt; CSV -&gt; Hotfix paste all stuff here. Now recover your saved variables like i mentioned before Addons,AccountData etc. Now you can play the game use terminal thing to open the game. BUT some strange bug here. If u already click the icon on the wow login screen remember my account name, untick it. If you struggle when you first time trying to login it will say connecting but it wont connect dont wait. Just cancel it untick the remember account name part and reopen the game and write your account name manually all the time until this strange bug fix. Hope it works cuz it worked on me (M1 Pro MacBook)
