### ISSUE TITLE
MacOS can't running

### ISSUE THREAD

**Issue by Se7enJoy** [0blu/WinterspringLauncher#42]
Have a bug report:
Unable to patch '/Users/xxxxx/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv' (WinterspringLauncher.HermesDataPatches.Hotfix.ItemEffect1.csv)

System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/xxxxx/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllLines(String path, Encoding encoding)
   at WinterspringLauncher.LauncherActions.<PrepareHermesProxyData>g__PatchCsvFiles|19_2(List`1 patchResources, String replace, String csvDirPath, <>c__DisplayClass19_0&) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 449
   at WinterspringLauncher.LauncherActions.PrepareHermesProxyData(String hermesPath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 417
   at WinterspringLauncher.Launcher.<>c__DisplayClass1_0.<Main>b__5() in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 72
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 152

**Comment by 0blu** [comment]
I cant test this right now, but apparently this helps
https://github.com/0blu/WinterspringLauncher/issues/40#issuecomment-1775994625

ref: https://github.com/0blu/WinterspringLauncher/issues/41

**Comment by Se7enJoy** [comment]
The software has automatically updated the latest version of HermesProxy<Release v3.10 (2023-10-19)>, but cannot automatically perform hotfixes.
The MacOS system version is 14.0 (23A344).

**Comment by Se7enJoy** [comment]
Hi,I solved the startup problem through the NEW solution. I have encountered the next issue again: How to download and replace WOW clients that support Chinese language
