### ISSUE TITLE
It doesn't work, if you choose the EU server

### ISSUE THREAD

**Issue by Artemiosss** [0blu/WinterspringLauncher#50]
When you choose the chinese server, the launcher runs without problems.
When you choose the EU server, it doesn't download the client:

"Downloading WoW Client...
Download URL: https://download.wowdl.net/downloadFiles/Clients/WoW%20Classic%201.14.2.42597%20All%20Languages.rar
Download Location: D:\WoW 1.14.2\winterspring-data\WoW 1.14.2 Everlook.partial-download
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).))
 ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 403 (Forbidden).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WinterspringLauncher.Utils.ProgressiveFileDownloader.DownloadFileFromHttpResponseMessage(HttpResponseMessage response) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Utils\ProgressiveFileDownloader.cs:line 52
   at WinterspringLauncher.Utils.ProgressiveFileDownloader.StartGetDownload() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Utils\ProgressiveFileDownloader.cs:line 47
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WinterspringLauncher.LauncherActions.DownloadFile(String downloadUrl, String downloadDestLocation, DownloadProgressInfoHandler progressInfoHandler) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherActions.cs:line 32
   at WinterspringLauncher.LauncherLogic.RunDownload(String downloadUrl, String destLocation) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.cs:line 121
   at WinterspringLauncher.LauncherLogic.<>c__DisplayClass11_0.<<StartGame>b__0>d.MoveNext() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.StartGame.cs:line 113
   --- End of inner exception stack trace ---

**Comment by ycwjw2010** [comment]
403 Forbidden，这不是简易明了嘛~  你没用VPN，ip被禁了。中文客户端是从国内镜像下载的，它在贵州，所以下载没问题。建议你把问题关了

**Comment by Artemiosss** [comment]
> 403 Forbidden，这不是简易明了嘛~ 你没用VPN，ip被禁了。中文客户端是从国内镜像下载的，它在贵州，所以下载没问题。建议你把问题关了

I can download the client directly, the link works without problems. No VPN needed. Though, the app can't download, the client.
